[VAS-735] Change default timeout for Station type A primitive
pagopa/pagopa-selfcare-ms-backoffice-backend pull request #314
Opened 2024-02-20 09:53 UTC by gioelemella

#### List of Changes

- Changed default timeout for Station type A primitive to `7`

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-20 11:18 UTC, jacopocarlini commented on src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
> +        stationDetails.setTimeoutA(7L);
does it need for channels too?

2024-02-20 13:24 UTC, jacopocarlini requested changes
I think we have to fix the FE too

2024-02-20 13:36 UTC, gioelemella commented on src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
> +        stationDetails.setTimeoutA(7L);
Stefano said only stations.

2024-02-21 09:41 UTC, jacopocarlini approved these changes

2024-02-21 09:42 UTC, merged