fix: Fixed getPaymentReceiptDetail openapi specs
pagopa/pagopa-selfcare-ms-backoffice-backend pull request #357
Opened 2024-04-10 09:28 UTC by svariant

#### List of Changes

- Improved getPaymentReceiptDetail openapi specs

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-04-10 10:03 UTC, gioelemella approved these changes
🍀

2024-04-10 14:57 UTC, jacopocarlini requested changes

2024-04-10 14:57 UTC, jacopocarlini commented on src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentsReceiptsController.java
> +    @GetMapping(value = "/{organization-tax-code}/detail/{iuv}", produces = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE})
why JSON?

2024-04-12 07:39 UTC, jacopocarlini approved these changes

2024-04-15 13:37 UTC, merged