[VAS-1195] New CI IBANs Mongo Collection
pagopa/pagopa-selfcare-ms-backoffice-backend pull request #457
Opened 2024-07-17 09:21 UTC by jacopocarlini

#### List of Changes

➕ Added a new collection `creditorInstitutionIbans` 
✏️ Edited the cron job to save the ibans in the new collection

#### Motivation and Context

#### How Has This Been Tested?

✋ Manually

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-17 15:41 UTC, alessio-cialini approved these changes

2024-07-17 15:41 UTC, gioelemella requested changes
Format the openapi

2024-07-17 15:41 UTC, gioelemella commented on openapi/openapi.json
Format the openapi

2024-07-18 07:30 UTC, jacopocarlini commented on openapi/openapi.json
done

2024-07-18 07:31 UTC, gioelemella approved these changes
💯

2024-07-18 07:47 UTC, merged